.TH "AbilityUI" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbilityUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClickableUIElement\fP, and \fBIInit< UnitCastingHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBUnitCastingHandler\fP abilityCaster)"
.br
.ti -1c
.RI "override void \fBShow\fP ()"
.br
.ti -1c
.RI "override void \fBHide\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBaseAbility\fP \fBBaseAbility\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< \fBAbilityUI\fP > \fBOnAbilityClick\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void AbilityUI\&.Hide ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.
.SS "override void AbilityUI\&.OnClick (PointerEventData eventData)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBClickableUIElement\fP\&.
.SS "override void AbilityUI\&.Show ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
