.TH "Affector" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Affector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAffector\fP (\fBBaseUnit\fP owner)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action< \fBEffectable\fP, \fBAffector\fP, \fBStatusEffect\fP > \fBOnAffect\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBaseUnit\fP \fBOwner\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
