.TH "ArchedShot" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArchedShot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTargetedShot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFire\fP (\fBBaseUnit\fP shooter, \fBBaseAbility\fP givenAbility, Vector2 dir, \fBBaseUnit\fP target, Vector3 archSize)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDisable\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void ArchedShot\&.Disable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBTargetedShot\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
