.TH "BaseUnitConfig" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseUnitConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBEnemyConfig\fP, and \fBShamanConfig\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "Sprite \fBUnitSprite\fP\fC [get]\fP"
.br
.ti -1c
.RI "Sprite \fBUnitIcon\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBStatSheet\fP \fBBaseStats\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
