.TH "BgMusicManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BgMusicManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< BgMusicManager >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlayMusic\fP ()"
.br
.ti -1c
.RI "void \fBStopMusic\fP ()"
.br
.ti -1c
.RI "void \fBChangeMusicVolume\fP (float volume)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "AudioSource \fBAudioSource\fP\fC [get]\fP"
.br
.ti -1c
.RI "AudioReverbFilter \fBAudioReverbFilter\fP\fC [get]\fP"
.br
.ti -1c
.RI "AudioLowPassFilter \fBAudioLowPassFilter\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
