.TH "CameraSettings" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetAsCameraSetting\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBMoveSpeedMinimum\fP = 5f"
.br
.ti -1c
.RI "float \fBCameraSpeedZoomChangeValue\fP = 4f"
.br
.ti -1c
.RI "float \fBCameraDragPanSpeed\fP = 7f"
.br
.ti -1c
.RI "float \fBEdgeScrollDetectSizeX\fP = 0\&.025f"
.br
.ti -1c
.RI "float \fBEdgeScrollDetectSizeY\fP = 0\&.025f"
.br
.ti -1c
.RI "float \fBXDamping\fP = 0\&.2f"
.br
.ti -1c
.RI "float \fBYDamping\fP = 0\&.2f"
.br
.ti -1c
.RI "float \fBEventTransitionDampingX\fP = 0\&.4f"
.br
.ti -1c
.RI "float \fBEventTransitionDampingY\fP = 0\&.4f"
.br
.ti -1c
.RI "float \fBZoomSpeed\fP = 6\&.5f"
.br
.ti -1c
.RI "float \fBZoomChangeValue\fP = 1f"
.br
.ti -1c
.RI "float \fBZoomDefaultStartValue\fP = 7f"
.br
.ti -1c
.RI "float \fBZoomMinClamp\fP = 2f"
.br
.ti -1c
.RI "float \fBZoomMaxClamp\fP = 14f"
.br
.ti -1c
.RI "bool \fBRightClickToPanCamera\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
