.TH "CameraHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCameraLevelSettings\fP (\fBCameraLevelSettings\fP cameraLevelSettings)"
.br
.ti -1c
.RI "void \fBResetCamera\fP ()"
.br
.ti -1c
.RI "void \fBLockCamera\fP (Vector2 lockedCameraPos, int lockedCameraZoom)"
.br
.ti -1c
.RI "void \fBSetCameraPosition\fP (Vector2 eventPosition, bool lockCameraMove=false)"
.br
.ti -1c
.RI "void \fBSetCameraZoom\fP (int zoom)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Volume \fBPostProcessVolume\fP\fC [get]\fP"
.br
.ti -1c
.RI "Camera \fBMainCamera\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
