.TH "ClickHelper" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClickHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerClickHandler, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsHover\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< PointerEventData\&.InputButton > \fBOnClick\fP"
.br
.ti -1c
.RI "Action \fBOnEnterHover\fP"
.br
.ti -1c
.RI "Action \fBOnExitHover\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
