.TH "CoreTemple" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreTemple
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBTakeDamage\fP (int amount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action \fBOnCoreDestroyed\fP"
.br
.ti -1c
.RI "Action< int > \fBOnGetHit\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMaxHp\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCurHp\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
