.TH "CounterUIElement" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CounterUIElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUIElement\fP\&.
.PP
Inherited by \fBCoreHPUIHnadler\fP, and \fBWaveCountUIHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBElementInit\fP (int maxValue, int currentValue=\-1)"
.br
.ti -1c
.RI "sealed override void \fBShow\fP ()"
.br
.ti -1c
.RI "abstract void \fBInit\fP ()"
.br
.RI "instantiate ElementInit  "
.ti -1c
.RI "sealed override void \fBUpdateVisual\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateUIData\fP (int value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "abstract void CounterUIElement\&.Init ()\fC [pure virtual]\fP"

.PP
instantiate ElementInit  
.PP
Implemented in \fBCoreHPUIHnadler\fP, and \fBWaveCountUIHandler\fP\&.
.SS "sealed override void CounterUIElement\&.Show ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.
.SS "sealed override void CounterUIElement\&.UpdateVisual ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
