.TH "DamageHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DamageHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDamageHandler\fP (float baseAmount)"
.br
.ti -1c
.RI "void \fBAddMod\fP (float mod)"
.br
.ti -1c
.RI "void \fBAddFlatMod\fP (int flatMod)"
.br
.ti -1c
.RI "int \fBGetFinalDamage\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
