.TH "DamageDealer" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DamageDealer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDamageDealer\fP (\fBBaseUnit\fP owner, \fBOffensiveAbility\fP autoAttack)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action< \fBDamageable\fP, \fBDamageDealer\fP, \fBDamageHandler\fP, \fBBaseAbility\fP, bool > \fBOnHitTarget\fP"
.br
.ti -1c
.RI "Action< \fBDamageable\fP, \fBDamageDealer\fP, \fBDamageHandler\fP, \fBBaseAbility\fP > \fBOnKill\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBaseUnit\fP \fBOwner\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
