.TH "Enemy" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseUnit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInit\fP (\fBBaseUnitConfig\fP givenConfig)"
.br
.ti -1c
.RI "void \fBToggleMove\fP (bool state)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEnemyConfig\fP \fBEnemyConfig\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCoreDamage\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsMoving\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBStatSheet\fP \fBBaseStats\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void Enemy\&.Init (\fBBaseUnitConfig\fP givenConfig)\fC [virtual]\fP"

.PP
Reimplemented from \fBBaseUnit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
