.TH "EnemyAnimator" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemyAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnitAnimator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInit\fP (\fBBaseUnit\fP unit)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBMoveAnimation\fP ()"
.br
.ti -1c
.RI "override void \fBDeathAnimation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void EnemyAnimator\&.DeathAnimation ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUnitAnimator\fP\&.
.SS "override void EnemyAnimator\&.Init (\fBBaseUnit\fP unit)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnitAnimator\fP\&.
.SS "override void EnemyAnimator\&.MoveAnimation ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBUnitAnimator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
