.TH "EnemySpawnPoint" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemySpawnPoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetIndicator\fP (Sprite artwork, float time, Action onClick)"
.br
.ti -1c
.RI "\fBEnemy\fP \fBSpawnEnemy\fP (\fBEnemyConfig\fP givenConf)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
