.TH "EnemyGroup" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemyGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetNumberOfSpawns\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnemyConfig\fP \fBEnemy\fP"
.br
.ti -1c
.RI "int \fBAmountPerSpawn\fP"
.br
.ti -1c
.RI "int \fBTotalAmount\fP"
.br
.ti -1c
.RI "int \fBSpawnedAtInterval\fP"
.br
.ti -1c
.RI "int \fBSpawnerIndex\fP"
.br
.ti -1c
.RI "int \fBNumSpawned\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
