.TH "GameManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< GameManager >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetLevelConfig\fP (\fBLevelConfig\fP levelConfig)"
.br
.ti -1c
.RI "void \fBQuit\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBISceneHandler\fP \fBSceneHandler\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBLevelConfig\fP \fBCurrentLevelConfig\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCameraHandler\fP \fBCameraHandler\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void GameManager\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBMonoSingleton< GameManager >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
