.TH "GAME_TIME" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GAME_TIME
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetTimeStep\fP (float time, float transitionTime=1, AnimationCurve curve=null)"
.br
.ti -1c
.RI "static void \fBPlay\fP ()"
.br
.ti -1c
.RI "static void \fBPause\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static float \fBTimePlayed\fP\fC [get]\fP"
.br
.ti -1c
.RI "static float \fBGetCurrentTimeRate\fP\fC [get]\fP"
.br
.ti -1c
.RI "static float \fBGameTime\fP\fC [get]\fP"
.br
.ti -1c
.RI "static float \fBGameDeltaTime\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsTimeStopped\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action \fBOnTimeRateChange\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
