.TH "HeroSelectionUI" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeroSelectionUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< HeroSelectionUI >\fP, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (\fBShaman\fP shaman)"
.br
.ti -1c
.RI "void \fBUpdateStatBlocks\fP (StatType shamanStatType, int newValue)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBMouseOverUI\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action \fBOnMouseEnter\fP"
.br
.ti -1c
.RI "Action \fBOnMouseExit\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
