.TH "HP_Bar" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HP_Bar
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (float max, UnitType entityType)"
.br
.ti -1c
.RI "void \fBInit\fP (float max)"
.br
.ti -1c
.RI "void \fBSetBarValue\fP (int value)"
.br
.ti -1c
.RI "void \fBSetBarValueSmoothly\fP (float value)"
.br
.ti -1c
.RI "void \fBSetBarValue\fP (\fBDamageable\fP arg1, \fBDamageDealer\fP arg2, \fBDamageHandler\fP arg3, \fBBaseAbility\fP arg4)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
