.TH "IdleState" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdleState
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCoroutineState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBIsLegal\fP ()"
.br
.ti -1c
.RI "override void \fBOnStateEnter\fP ()"
.br
.ti -1c
.RI "override void \fBOnStateExit\fP ()"
.br
.ti -1c
.RI "override IEnumerator \fBRunState\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override bool IdleState\&.IsLegal ()\fC [virtual]\fP"

.PP
Implements \fBCoroutineState\fP\&.
.SS "override void IdleState\&.OnStateEnter ()\fC [virtual]\fP"

.PP
Implements \fBCoroutineState\fP\&.
.SS "override void IdleState\&.OnStateExit ()\fC [virtual]\fP"

.PP
Implements \fBCoroutineState\fP\&.
.SS "override IEnumerator IdleState\&.RunState ()\fC [virtual]\fP"

.PP
Implements \fBCoroutineState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
