.TH "IInit< T1, T2 >" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IInit< T1, T2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBInit\fP (T obj)"
.br
.ti -1c
.RI "abstract void \fBInit\fP (T1 obj1, T2 obj2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
