.TH "Indicator" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Indicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitIndicator\fP (\fBIndicatable\fP target, Sprite artwork, float time=0, bool clickable=false, Action onClick=null)"
.br
.ti -1c
.RI "void \fBInvokeClick\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
