.TH "ISceneHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISceneHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSceneHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadScene\fP (SceneType sceneType)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
