.TH "LerpValuesHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LerpValuesHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< LerpValuesHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetValueByType< T >\fP (\fBLerpValueConfig\fP config, T type, float currentValue, float newValue, Action< T, float > setter)"
.br
.ti -1c
.RI "void \fBSetValueByType< T >\fP (T type, float currentValue, float newValue, Action< T, float > setter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void LerpValuesHandler\&.SetValueByType< T > (\fBLerpValueConfig\fP config, T type, float currentValue, float newValue, Action< T, float > setter)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIEnum\fP
.SS "void LerpValuesHandler\&.SetValueByType< T > (T type, float currentValue, float newValue, Action< T, float > setter)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIEnum\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
