.TH "LevelManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< LevelManager >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEndLevel\fP (bool win)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBScoreHandler\fP \fBScoreHandler\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBLevelHandler\fP \fBCurrentLevel\fP\fC [get]\fP"
.br
.ti -1c
.RI "List< \fBShaman\fP > \fBShamanParty\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsWon\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSelectionManager\fP \fBSelectionManager\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIndicatorManager\fP \fBIndicatorManager\fP\fC [get]\fP"
.br
.ti -1c
.RI "Canvas \fBGameUi\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBPoolManager\fP \fBPoolManager\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
