.TH "LevelConfig" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShamanConfig\fP[] \fBShamans\fP"
.br
.ti -1c
.RI "\fBLevelHandler\fP \fBlevelPrefab\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
