.TH "ObjectPool< T >" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectPool< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "T \fBGetPooledObject\fP ()"
.br
.ti -1c
.RI "bool \fBCheckActiveIstance\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBPrefabToPool\fP"
.br
.ti -1c
.RI "int \fBNumToPool\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< T > \fBPooledObjects\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
