.TH "OffensiveAbility" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OffensiveAbility
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseAbility\fP\&.
.PP
Inherited by \fBMultiShot\fP, \fBPiercingShot\fP, and \fBShamanAutoAttack\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBaseDamage\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBTargetData\fP \fBTargetData\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBRange\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
