.TH "PartyUIManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartyUIManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBShow\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void PartyUIManager\&.Show ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
