.TH "PoolManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PoolManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBProjectilePool\fP \fBTestAbilityPool\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBTargetedShotPool\fP \fBShamanAutoAttackPool\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBEnemyPool\fP \fBEnemyPool\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIndicatorPool\fP \fBInidcatorPool\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBArchedShotPool\fP \fBArchedShotPool\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
