.TH "PowerStructureStatEffect" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PowerStructureStatEffect
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "StatType \fBStatType\fP"
.br
.ti -1c
.RI "Modifier \fBModifier\fP"
.br
.ti -1c
.RI "float[] \fBRingValues\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
