.TH "PowerStructureConfig" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PowerStructureConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBRange\fP"
.br
.ti -1c
.RI "float[] \fBRingsRanges\fP"
.br
.ti -1c
.RI "Color \fBRingDefaultColor\fP"
.br
.ti -1c
.RI "Color \fBPowerStructureTypeColor\fP"
.br
.ti -1c
.RI "float \fBDefaultSpriteAlpha\fP"
.br
.ti -1c
.RI "float \fBSpriteAlphaFade\fP"
.br
.ti -1c
.RI "Sprite \fBPowerStructureSprite\fP"
.br
.ti -1c
.RI "\fBPowerStructureStatEffect\fP \fBstatEffect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
