.TH "ProjectilePool" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectilePool
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectPool< Projectile >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
