.TH "ProximityRingHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProximityRingHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (int id, float alpha)"
.br
.ti -1c
.RI "void \fBScale\fP (float range)"
.br
.ti -1c
.RI "void \fBToggleSprite\fP (bool state)"
.br
.ti -1c
.RI "void \fBChangeColor\fP (Color color)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< int, \fBShadow\fP > \fBOnShadowEnter\fP"
.br
.ti -1c
.RI "Action< int, \fBShadow\fP > \fBOnShadowExit\fP"
.br
.ti -1c
.RI "Action< int, \fBShaman\fP > \fBOnShamanEnter\fP"
.br
.ti -1c
.RI "Action< int, \fBShaman\fP > \fBOnShamanExit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
