.TH "SceneEditor" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits OdinMenuEditorWindow\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewSceneClass\fP"
.br
.ti -1c
.RI "class \fBSceneEditorCache\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBPath\fP (SceneType path)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "override OdinMenuTree \fBBuildMenuTree\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
