.TH "SceneHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBISceneHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadScene\fP (SceneType sceneType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static Scene \fBPresistanteScene\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Scene \fBCurrentScene\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsLoading\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action< SceneType > \fBOnSceneLoaded\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SceneHandler\&.LoadScene (SceneType sceneType)"

.PP
Implements \fBISceneHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
