.TH "SceneEditor.SceneEditorCache" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneEditor.SceneEditorCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneEditorCache\fP (bool canBeDeleted, SceneAsset scene)"
.br
.ti -1c
.RI "void \fBLoadSingle\fP ()"
.br
.ti -1c
.RI "void \fBLoadAdditive\fP ()"
.br
.ti -1c
.RI "void \fBUnload\fP ()"
.br
.ti -1c
.RI "void \fBDelete\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action \fBOnSceneDeleted\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
