.TH "ScoreHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoreHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateScore\fP (int kills=0, int deaths=0, int assists=0)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBKills\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBDeaths\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAssists\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
