.TH "ShamanAutoAttack" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShamanAutoAttack
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOffensiveAbility\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCastAbility\fP (\fBBaseUnit\fP caster)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override bool ShamanAutoAttack\&.CastAbility (\fBBaseUnit\fP caster)\fC [virtual]\fP"

.PP
Reimplemented from \fBBaseAbility\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
