.TH "ShamanConfig" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShamanConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseUnitConfig\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBBaseAbility\fP > \fBKnownAbilities\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
