.TH "ShamanAnimator" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShamanAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnitAnimator\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBMoveAnimation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void ShamanAnimator\&.MoveAnimation ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBUnitAnimator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
