.TH "SlowMotionManager" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlowMotionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonoSingleton< SlowMotionManager >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartSlowMotionEffects\fP ()"
.br
.ti -1c
.RI "void \fBEndSlowMotionEffects\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
