.TH "StatusEffectConfig" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatusEffectConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBDuration\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAmount\fP\fC [get]\fP"
.br
.ti -1c
.RI "StatusEffectProcess \fBProcess\fP\fC [get]\fP"
.br
.ti -1c
.RI "StatType \fBStatTypeAffected\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
