.TH "StatSheet" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatSheet
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCalcDamageMitigation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBaseStat\fP \fBMaxHp\fP = new \fBBaseStat\fP(StatType\&.MaxHp)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBBaseDamage\fP = new \fBBaseStat\fP(StatType\&.BaseDamage)"
.br
.ti -1c
.RI "\fBBaseStatDecimal\fP \fBAttackSpeed\fP = new \fBBaseStatDecimal\fP(StatType\&.AttackSpeed)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBBaseRange\fP = new \fBBaseStat\fP(StatType\&.BaseRange)"
.br
.ti -1c
.RI "\fBBaseStatDecimal\fP \fBMovementSpeed\fP = new \fBBaseStatDecimal\fP(StatType\&.MovementSpeed)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBCritDamage\fP = new \fBBaseStat\fP(StatType\&.CritDamage)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBCritChance\fP = new \fBBaseStat\fP(StatType\&.CritChance)"
.br
.ti -1c
.RI "\fBBaseStatDecimal\fP \fBInvincibleTime\fP = new \fBBaseStatDecimal\fP(StatType\&.InvincibleTime)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBAbilityCooldownReduction\fP = new \fBBaseStat\fP(StatType\&.AbilityCooldownReduction)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBArmor\fP = new \fBBaseStat\fP(StatType\&.Armor)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBHpRegen\fP = new \fBBaseStat\fP(StatType\&.HpRegen)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBBonusStatusEffectDuration\fP = new \fBBaseStat\fP(StatType\&.BonusStatusEffectDuration)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBAbilityProjectileSpeed\fP = new \fBBaseStat\fP(StatType\&.AbilityProjectileSpeed)"
.br
.ti -1c
.RI "\fBBaseStat\fP \fBAbilityProjectilePenetration\fP = new \fBBaseStat\fP(StatType\&.AbilityProjectilePenetration)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
