.TH "StatBarHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatBarHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBBaseUnit\fP unit)"
.br
.ti -1c
.RI "void \fBUpdateStatBarHealth\fP (\fBDamageable\fP damageable, \fBDamageDealer\fP arg2, \fBDamageHandler\fP arg3, \fBBaseAbility\fP arg4, bool arg5)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "StatBarType \fBStatBarType\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
