.TH "TargetedShot" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TargetedShot
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBArchedShot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFire\fP (\fBBaseUnit\fP shooter, \fBBaseAbility\fP givenAbility, Vector2 dir, \fBBaseUnit\fP target)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRotate\fP (Vector2 dir)"
.br
.ti -1c
.RI "virtual void \fBDisable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "\fBBaseAbility\fP \fBability\fP"
.br
.ti -1c
.RI "\fBBaseUnit\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBBaseUnit\fP \fBtarget\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
