.TH "TimeButtonsUI" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeButtonsUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClickableUIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetState\fP (bool state)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< \fBTimeButtonsUI\fP > \fBOnTurnOn\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void TimeButtonsUI\&.OnClick (PointerEventData eventData)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBClickableUIElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
