.TH "Tzipory.GameplayLogic.Managers.MainMenuMangers" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tzipory.GameplayLogic.Managers.MainMenuMangers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainMenuManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
