.TH "UnitTargetHelper" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTargetHelper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitTargetHelper\fP (\fBBaseUnit\fP givenOwner)"
.br
.ti -1c
.RI "\fBBaseUnit\fP \fBGetTarget\fP (List< \fBBaseUnit\fP > targets, \fBTargetData\fP givenData, List< \fBBaseUnit\fP > targetsToAvoid=null, StatType stat=StatType\&.AttackSpeed)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< \fBBaseUnit\fP > \fBOnTarget\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
