.TH "UnitMovement" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitMovement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP (\fBBaseUnit\fP givenOwner)"
.br
.ti -1c
.RI "void \fBSetDest\fP (Vector3 worldPos)"
.br
.ti -1c
.RI "void \fBToggleMovement\fP (bool state)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action \fBOnDestenationSet\fP"
.br
.ti -1c
.RI "Action \fBOnDestenationReached\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsMoving\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
