.TH "UnitCastingHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitCastingHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitCastingHandler\fP (\fBBaseUnit\fP owner, \fBBaseAbility\fP ability)"
.br
.ti -1c
.RI "float \fBGetAbilityCD\fP ()"
.br
.ti -1c
.RI "void \fBCastAbility\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBaseAbility\fP \fBAbility\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBLastCast\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBBaseUnit\fP \fBUnit\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
