.TH "UnitStats" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitStats
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitStats\fP (\fBStatSheet\fP baseStats)"
.br
.ti -1c
.RI "float \fBGetStatValue\fP (StatType statTypeId)"
.br
.ti -1c
.RI "float \fBGetBaseStatValue\fP (StatType statTypeId)"
.br
.ti -1c
.RI "void \fBAddValueToStat\fP (StatType statType, int value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action< StatType, float > \fBOnStatChanged\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMaxHp\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBBaseDamage\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBAttackSpeed\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBBonusRange\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBMovementSpeed\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCritDamage\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCritChance\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBInvincibleTime\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAbilityCooldownReduction\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBArmor\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBHpRegen\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBBonusStatusEffectDuration\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAbilityProjectileSpeed\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAbilityProjectilePenetration\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
