.TH "WaveCountUIHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WaveCountUIHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCounterUIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.RI "instantiate ElementInit  "
.ti -1c
.RI "override void \fBElementInit\fP (int maxValue, int currentValue=\-1)"
.br
.ti -1c
.RI "override void \fBHide\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void WaveCountUIHandler\&.ElementInit (int maxValue, int currentValue = \fC\-1\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBCounterUIElement\fP\&.
.SS "override void WaveCountUIHandler\&.Hide ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUIElement\fP\&.
.SS "override void WaveCountUIHandler\&.Init ()\fC [virtual]\fP"

.PP
instantiate ElementInit  
.PP
Implements \fBCounterUIElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
