.TH "WaveData" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WaveData
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCalcSpawns\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBEnemySpawnData\fP > \fBwaves\fP = new List<\fBEnemySpawnData\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBBetweenWavesInterval\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBStartDelayInterval\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
