.TH "WindEffectHandler" 3 "Mon Jan 29 2024" "Version 0.096" "WitchPack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindEffectHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEffectTransitionLerp< WindParticleAnimationType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (ParticleSystem[] windParticles)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetValue\fP (WindParticleAnimationType type, float value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WitchPack from the source code\&.
